const slides=[...document.querySelectorAll('#slides>section')];let current=0,busy=false;
const main=document.querySelector('#slides'),overview=document.querySelector('#overview'),grid=document.createElement('div');grid.className='project-menu';
const summaries=['面向打印质检，辅助识别缺陷、定位问题，减少人工检查负担。','面向打印故障排查，提供原因分析和参数建议，减少盲目试错。','面向短局娱乐，通过自动战斗、零件拼装与融合，体验不断变化的生存流派。','面向求职与交流，集中呈现经历和成果，方便快速了解。','面向作品展示，集中整理照片、查看细节，解决素材分散问题。','面向内容 IP 研究，聚合多平台热榜与真实历史记录，查看关注度变化。','面向工作留痕与复盘，集中记录工作、归档项目，减少总结整理成本。','面向航空运行安全，通过 DEMATEL-ISM、熵值法与云模型评估 27 项风险指标，划分层级并输出综合风险评分。','面向办公采光与防眩光，用外层玻璃与内层百叶双层结构构建交互模型，切换情境并实时计算视线遮挡与直射路径。','面向钢铁产业供应链金融，以钢银电商为案例分析三大产品模式，结合风险事件研究信用风控体系改进。','面向生鲜电商供应链，以叮咚买菜前置仓为案例，对比每日优鲜路径，剖析履约成本结构与盈利逻辑。','面向 Agent 迭代，计划评估任务表现、分析失败原因，辅助改进。'];
const progress=document.querySelector('#progress');progress.setAttribute('role','group');progress.setAttribute('aria-label','Choose project');
const dots=slides.map((slide,i)=>{const dot=document.createElement('button');dot.className='project-dot';dot.setAttribute('aria-label',slide.querySelector('h2').textContent);dot.onclick=()=>transition(()=>{document.body.classList.remove('all');go(i)});progress.append(dot);return dot;});
function go(n){current=(n+slides.length)%slides.length;slides.forEach((s,i)=>s.classList.toggle('active',i===current));document.querySelector('#count').textContent=`${current+1} / ${slides.length}`;dots.forEach((dot,i)=>dot.setAttribute('aria-pressed',String(i===current)));}
function transition(fn){if(busy)return;busy=true;main.classList.add('switching');setTimeout(()=>{fn();overview.setAttribute('aria-pressed',String(document.body.classList.contains('all')));main.classList.remove('switching');window.scrollTo(0,0);busy=false},matchMedia('(prefers-reduced-motion: reduce)').matches?0:260)}
const filterBar=document.createElement('div');filterBar.className='project-filter';
const filterDefs=[['all','全部'],['learning','学习'],['interest','兴趣'],['idea','想法'],['assignment','作业']];
const filterBtns=filterDefs.map(([key,label])=>{const btn=document.createElement('button');btn.className='filter-btn'+(key==='all'?' active':'');btn.textContent=label;btn.dataset.filter=key;filterBar.append(btn);return btn});
function applyFilter(key){filterBtns.forEach(b=>b.classList.toggle('active',b.dataset.filter===key));grid.querySelectorAll('.project-choice').forEach(b=>{b.style.display=(key==='all'||b.dataset.category===key)?'':'none'})}
filterBtns.forEach(b=>b.onclick=()=>applyFilter(b.dataset.filter));
slides.forEach((slide,i)=>{const b=document.createElement('button');b.className='project-choice';b.dataset.category=slide.dataset.category;const h=document.createElement('h2'),p=document.createElement('p');h.textContent=slide.querySelector('h2').textContent;p.textContent=summaries[i];const image=slide.querySelector("aside").cloneNode(true);image.removeAttribute("class");image.className="menu-preview";b.append(image,h,p);const status=slide.querySelector(".project-status");if(status)h.append(document.createTextNode(" "),status.cloneNode(true));b.onclick=()=>transition(()=>{document.body.classList.remove('all');go(i)});grid.append(b)});const upcoming=document.createElement('a');upcoming.className='project-upcoming';upcoming.href='https://github.com/FaaaQwQ';upcoming.target='_blank';upcoming.rel='noopener';upcoming.setAttribute('aria-label','持续开发中，访问 GitHub');const plus=document.createElement('span');plus.className='upcoming-plus';plus.textContent='+';plus.setAttribute('aria-hidden','true');const label=document.createElement('span');label.textContent='持续开发中';upcoming.append(plus,label);grid.append(upcoming);main.append(filterBar);main.append(grid);
overview.onclick=()=>transition(()=>document.body.classList.toggle('all'));overview.setAttribute('aria-pressed','false');document.querySelector('#theme').onclick=()=>document.body.classList.toggle('dark');document.addEventListener('keydown',e=>{if(document.body.classList.contains('all'))return;if(e.key==='ArrowRight')go(current+1);if(e.key==='ArrowLeft')go(current-1)});go(0);

